name: Trivy Image Scan Workflow

on:
  workflow_dispatch:

jobs:
  pull-image:
    name: Pull Docker Image
    runs-on: ubuntu-latest


  trivy-scan:
    name: Scan Docker Image with Trivy
    runs-on: ubuntu-latest
    needs: pull-image

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: python:3.8
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif