name: Trivy Image Scan Workflow

on:
  workflow_dispatch:

jobs:
  pull-image:
    name: Pull Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Pull Python Docker image
        run: docker pull alpine:3.20

  trivy-scan:
    name: Scan Docker Image with Trivy
    runs-on: ubuntu-latest
    needs: pull-image

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy image scan
        uses: aquasecurity/trivy-action@v0.4.0
        with:
          image-ref: alpine:3.20
          format: sarif
          output: trivy-results.sarif

      - name: Upload scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif

      - name: Hello World test
        run: echo "✅ Workflow is running!"
